#!/bin/sh

stop(){
state=`docker inspect --format {{.State.Running}} "${NAME}" 2>/dev/null`
	if [ "$state" == "true" ]; then
		printf "Stop: "
		docker stop "${NAME}"
		printf "Remove: "
		docker rm "${NAME}"
	elif [ "$state" == "false" ]; then
		printf "Stop: "
		docker rm "${NAME}";
	fi
}

run(){

RUN_CMD="docker run -h ${NAME} \
-it \
--net none \
-d \
--name ${NAME} \
-v /var/run/docker.sock:/var/run/docker.sock \
-v /etc/docker-gc-exclude:/etc/docker-gc-exclude \
${CONTAINER_RUN_OPTS} \
${TAG}"

    echo "Command: ${RUN_CMD}"
    printf "Run: "
    eval "${RUN_CMD}"
}


. env && \
./build && \
stop && \
run

